---
name: Docker Release

on:
  push:
    tags:
      '*'

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Lint Code Base
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Get Git Tag
        run: |
          GIT_TAG=$(echo "${GITHUB_REF##*/}")
          echo "${GIT_TAG}"
          echo "GIT_TAG=${GIT_TAG}" >> $GITHUB_ENV
      -
        name: Get Git SHA
        run: |
          GIT_SHA=$(echo "${GITHUB_SHA: -8}")
          echo "${GIT_SHA}"
          echo "GIT_SHA=${GIT_SHA}" >> $GITHUB_ENV
      -
        name: Get Version
        run: |
          VERSION=$(cat VERSION)
          echo "${VERSION}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      -
        name: Create Docker Meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: dsavell/baseimage-minideb
          tag-custom: |
             latest
             ${{ env.VERSION }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            VERSION=${{ env.VERSION }}
