---
name: dockerCI

#on:
#  push:
#    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      #- name: Login to DockerHub
      #  uses: docker/login-action@v1
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Hadolint Dockerfile
        used: brpaz/hadolint-action@v1.2.1
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: dsavell/baseimage-minideb
      #- name: Docker Build and Push
      #  uses: docker/build-push-action@v2
      #  with:
      #    push: true
      #    tags: user/app:latest
