---
name: Docker Validate

on: push

jobs:
  docker-validate:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Lint Code Base
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Get Version
        id: getVersion
        run: |
          VERSION=$(cat VERSION)
          echo "${VERSION}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      -
        name: Test Docker Build
        uses: docker/build-push-action@v2
        with:
          images: dsavell/baseimage-minideb
          push: false
          build-args: |
            VERSION=${{ env.VERSION }}
      -
        name: Run Snyk
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: dsavell/baseimage-minideb
          args: --file=Dockerfile
      -
        name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
